name = "utang-tracker"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"
[vars]
VITE_SUPABASE_URL = "https://iutytlcrjoyestcxgvtn.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1dHl0bGNyam95ZXN0Y3hndnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MDI5MzEsImV4cCI6MjA5NDA3ODkzMX0.30E1sFunPWYnc1lq0ZHMT2m7zbKsBLJQf-km2tB2F4U"